FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD angular.jar /opt/angular/
EXPOSE 8080
WORKDIR /opt/angular/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "angular.jar"]
